adafruit/Adafruit_IO_Arduino

- src/AdafruitIO.cpp
- src/AdafruitIO.h
- src/AdafruitIO_Ethernet.h
- src/AdafruitIO_FONA.h
- src/util/AdafruitIO_Board.cpp
- src/util/AdafruitIO_Board.h
- src/wifi/AdafruitIO_ESP8266.cpp
- src/wifi/AdafruitIO_ESP8266.h
- src/wifi/AdafruitIO_MKR1000.cpp
- src/wifi/AdafruitIO_MKR1000.h
- src/wifi/AdafruitIO_WICED.cpp
- src/wifi/AdafruitIO_WICED.h
- src/wifi/AdafruitIO_WINC1500.cpp
- src/wifi/AdafruitIO_WINC1500.h
* adds unique id helper function for all supported boards
* adds mcu type helper function
* adds io lib version helper function
* adds connection type (wifi, fona, ethernet, etc) helper function
* adds user agent helper function
feather fona 32u4:
```
unique id: 1e5d955b875bffff00fffff7ffff583435363431150e1414170b12081308ffff
board type: feather_32u4
connection type: fona
version: 2.0.0
user agent: AdafruitIO-Arduino/2.0.0 (feather_32u4-fona)
```
feather esp8266:
```
unique id: 151f55
board type: esp8266
connection type: wifi
version: 2.0.0
user agent: AdafruitIO-Arduino/2.0.0 (esp8266-wifi)
```
feather m0 winc1500:
```
unique id: 73633edc514d464646202020ff0f0837
board type: feather_m0
connection type: winc1500
version: 2.0.0
user agent: AdafruitIO-Arduino/2.0.0 (feather_m0-winc1500)
``` …
> Board Utility

- src/AdafruitIO_Dashboard.cpp
- src/AdafruitIO_Feed.cpp
- src/AdafruitIO_Group.cpp
- src/blocks/AdafruitIO_Block.cpp
this updates group, feed, dashboard, & block classes to support `v0.2.0` of the arduino HTTP client library.  there is an [unreleased `beginBody` API change](https://github.com/arduino-libraries/ArduinoHttpClient/commit/448a1520c892f7667ab11f9aa6141fd9d5376533) that adds request body support. `beginBody` is an alias for `endRequest`, so for now multiple calls to `endRequest` are used to support POST request bodies.
> ArduinoHttpClient v0.2.0 support

- src/AdafruitIO_Data.cpp
this supports quoted csv values in `toCSV` and `parseCSV`
> csv parsing fixes

- .gitignore
- README.md
- examples/adafruitio_01_subscribe/adafruitio_01_subscribe.ino
- library.properties
- src/AdafruitIO.cpp
- src/AdafruitIO.h
- src/AdafruitIO_Data.cpp
- src/AdafruitIO_Data.h
- src/AdafruitIO_Definitions.h
- src/AdafruitIO_Feed.cpp
- src/AdafruitIO_Feed.h
This change set includes a more comprehensive and accurate CSV parser and a new API method on the Feed object for retrieving the last value that was sent to the feed.
> Feed last value and accurate CSV parsing

- examples/adafruitio_00_publish/adafruitio_00_publish.ino
- examples/adafruitio_01_subscribe/adafruitio_01_subscribe.ino
- examples/adafruitio_02_pubsub/adafruitio_02_pubsub.ino
- examples/adafruitio_03_multiple_feeds/adafruitio_03_multiple_feeds.ino
- examples/adafruitio_04_location/adafruitio_04_location.ino
- examples/adafruitio_05_type_conversion/adafruitio_05_type_conversion.ino
- examples/adafruitio_07_digital_out/adafruitio_07_digital_out.ino
- examples/adafruitio_08_analog_in/adafruitio_08_analog_in.ino
- examples/adafruitio_09_analog_out/adafruitio_09_analog_out.ino
- examples/adafruitio_11_group_pub/adafruitio_11_group_pub.ino
- examples/adafruitio_13_rgb/adafruitio_13_rgb.ino
- examples/adafruitio_14_neopixel/adafruitio_14_neopixel.ino
- examples/adafruitio_16_servo/adafruitio_16_servo.ino
- src/AdafruitIO.cpp
- src/AdafruitIO_Feed.cpp
- src/AdafruitIO_Feed.h
This change adds support for Adafruit IO's new MQTT /get method that retriggers sending of the last value for a given feed. 
Because IO doesn't support the MQTT retain flag we need a different way to recall the last value published to a given feed. This library already includes a `feed->lastValue` method, but that uses the HTTP API, which can be finicky when used in combination with an MQTT connection. By keeping everything in MQTT, application code can be simpler and slightly more robust.
> Use /get MQTT topic to trigger resend of feed data.

- library.properties
- src/AdafruitIO_Data.cpp
**Scope:**
_src/AdafruitIO_Data.cpp:_
- Changed `toRed()`, `toBlue()`, `toGreen()`, `toNeoPixel()` to reflect changes proposed in https://github.com/adafruit/Adafruit_IO_Arduino/issues/56 by @supuflounder
> Patch color methods

- library.properties
- src/AdafruitIO_Data.cpp
Addressing https://github.com/adafruit/Adafruit_IO_Arduino/issues/76: Adding the ability to set the amount of precision points while sending a a double or float to Adafruit IO from non-esp8266 hardware.
> add prec. points to sending AVR and non-avr (SAMD/ESP32) targets

- examples/adafruitio_00_publish/config.h
- examples/adafruitio_01_subscribe/config.h
- examples/adafruitio_03_multiple_feeds/config.h
- examples/adafruitio_04_location/config.h
- examples/adafruitio_05_type_conversion/config.h
- examples/adafruitio_06_digital_in/config.h
- examples/adafruitio_07_digital_out/config.h
- examples/adafruitio_08_analog_in/config.h
- examples/adafruitio_09_analog_out/config.h
- examples/adafruitio_10_dashboard_creation/config.h
- examples/adafruitio_11_group_pub/config.h
- examples/adafruitio_12_group_sub/config.h
- examples/adafruitio_13_rgb/config.h
- examples/adafruitio_14_neopixel/config.h
- examples/adafruitio_15_temp_humidity/config.h
- examples/adafruitio_16_servo/config.h
- examples/adafruitio_17_time_subscribe/config.h
- examples/adafruitio_18_device_info/config.h
- examples/adafruitio_19_deepsleep/config.h
- examples/adafruitio_20_shared_feed_write/config.h
- examples/adafruitio_21_feed_read/config.h
- examples/adafruitio_22_environmental_monitor/config.h
- examples/adafruitio_23_ifttt/config.h
- examples/adafruitio_24_zapier/config.h
- examples/io_home_series/io_garage/config.h
- examples/io_home_series/io_home_security/config.h
- examples/io_home_series/neopixel_and_thermometer/config.h
- library.properties
Adafruit SAMD AirLift boards have redefinitions to use nina pin naming (via https://github.com/adafruit/ArduinoCore-samd/pull/131).
This pull request:
* Updates all example `config.h` files for compatibility with both Adafruit AirLift boards and Arduino WiFi boards (MKR1010/Uno WiFi Rev2), fixing https://github.com/adafruit/Adafruit_IO_Arduino/issues/90
* Updates all example `config.h` files with links to new Adafruit AirLift Shield and Feather product URLs
> Examples use WIFININA Pin Names

- docs/dependencies.rst
<https://github.com/espressif/arduino-esp32#using-through-arduino-ide> is no longer valid.
> Fix a wrong link

- library.properties
- src/AdafruitIO_Data.cpp
This PR adds support for float formatting on Arduino UNO Wifi Rev. 2.
Since that Arduino variant uses the "megaAVR" core, which has much of the same limitations as regular AVR cores, the `ARDUINO_ARCH_AVR` preprocessor check wasn't sufficient to catch this.
This issue was discovered by using said board to post decimal values to Adafruit IO.
Note: This does _not_ add support for board type and board ID - these will still be "unknown" as today.
> Add support for float formatting on Arduino UNO Wifi Rev. 2

- README.md
Fix badge to link to `repo/actions` URL instead of a static .svg image url
> Fix Actions Badge URL

- library.properties
- src/wifi/AdafruitIO_AIRLIFT.h
Fixes hang for AirLift Co-Processors during connect introduced in [3.3.1](https://github.com/adafruit/Adafruit_IO_Arduino/releases/tag/3.3.1).
Relevant Forum Issues:
https://forums.adafruit.com/viewtopic.php?f=56&t=164725
https://forums.adafruit.com/viewtopic.php?f=56&t=164620
---
Tested on Feather M4 and FeatherWing AirLift
Previous (v`3.5.1`) hang:
```
Connecting to Adafruit IO
1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.
```
This PR (v`3.6.0`): 
```
Connecting to Adafruit IO
Adafruit IO connected.
sending -> 0
....
sending -> 200
```
> Fix hang on connect for AirLift Co-Processors 

- src/AdafruitIO_Group.cpp
In AdafruitIO_Group::call there is a comparison with the feedname
of the update. If the onMessage() call didn't provide a feed name,
the feed pointer is null.  The code also checks for this, but
it does it after comparing with a string.  Reverse the check
so a short-circuiting or can do the right thing.
> Don't compare nullptr string - Fixes #120

- src/AdafruitIO_Ethernet.h
Fixes https://github.com/adafruit/Adafruit_IO_Arduino/issues/110 and https://github.com/adafruit/Adafruit_IO_Arduino/issues/112 by adding an ethernet disconnect function to stop active ethernetclient connections.
Prior to PR:
```
In file included from /Users/brentrubell/Documents/Arduino/adafruitio_02_pubsub/adafruitio_02_pubsub.ino:18:0:
config.h:17:21: error: cannot declare variable 'io' to be of abstract type 'AdafruitIO_Ethernet'
AdafruitIO_Ethernet io(IO_USERNAME, IO_KEY);
^~
In file included from /var/folders/k6/g066g1tn567fn8mj2p42x4240000gn/T/arduino_build_943460/sketch/config.h:16:0,
from /Users/brentrubell/Documents/Arduino/adafruitio_02_pubsub/adafruitio_02_pubsub.ino:18:
/Users/brentrubell/Documents/Arduino/libraries/Adafruit_IO_Arduino/src/AdafruitIO_Ethernet.h:35:7: note: …
```
> Add Ethernet disconnect function

- src/AdafruitIO_FONA.h
Related: https://github.com/adafruit/Adafruit_IO_Arduino/issues/134
Adding _disconnect function which disables GPRS and sets AIO network `_status`
NOTE: This PR is currently untested on hardware and is a draft pull request, will test tomorrow.
> Add _disconnect function to AdafruitIO_FONA.h

- library.properties
- src/wifi/AdafruitIO_ESP32.cpp
- src/wifi/AdafruitIO_ESP32.h
The latest ESP32 Arduino Core (1.0.6 and above) requires a call to `SecureWiFiClient.setCACert()` for TLS/SSL connections. The secure wifi client in previous versions didn’t require this function to be called in order to establish a connection with Adafruit IO's MQTT server.
This pull request updates the `AdafruitIO_ESP32.` wifi adapter files to include the root certificate and updated code.
Similar to https://github.com/adafruit/Adafruit_MQTT_Library/pull/192
> Update for ESP32

- .github/workflows/githubci.yml
- README.md
- library.properties
- src/AdafruitIO.h
- src/AdafruitIO_Data.cpp
- src/AdafruitIO_Definitions.h
- src/wifi/AdafruitIO_ESP8266.cpp
- src/wifi/AdafruitIO_ESP8266.h
Projects that require "Secure MQTT" (TLS/SSL) on ESP8266 also require a new SSL certificate + SSL fingerprint every year. 
* Warning/Info text has been added to `src/wifi/AdafruitIO_ESP8266.h` advising users to upgrade to the ESP32 platform if using SSL/TLS with an Adafruit IO Arduino project.
* For users who still want to experiment - existing lines have been commented out and instructions about compiling included.
* Fixed ESP32-BSP warnings
* Updated workflow file to perform manual installation of HTTPClient due to ESP32-BSP warnings
* Related: https://github.com/arduino-libraries/ArduinoHttpClient/issues/138
* Bumped semver, updated boards supported via README
Tested on an Adafruit Feather ESP8266 Huzzah running the publish+subscribe example within this library.
> Remove SSL for ESP8266 Platform

- library.properties
- src/AdafruitIO_Data.cpp
- src/AdafruitIO_Definitions.h
Fixes io.run () exception issue discussed on https://forums.adafruit.com/viewtopic.php?t=193560 and https://forums.adafruit.com/viewtopic.php?t=193603
Also adds the latest SSL cert for ESP8266 (even though commented out) per topic:
https://forums.adafruit.com/viewtopic.php?t=193572
----
Test Hardware: Adafruit Feather Huzzah ESP8266
Sketches Tested:
- [xraymike](https://forums.adafruit.com/memberlist.php?mode=viewprofile&u=242909)
- [adafruitio_05_type_conversion](https://github.com/adafruit/Adafruit_IO_Arduino/blob/master/examples/adafruitio_05_type_conversion/adafruitio_05_type_conversion.ino)
> Fix ESP8266 fallthrough patch causing memory error, add updated ssl cert

- library.properties
- src/AdafruitIO.cpp
- src/AdafruitIO.h
Reverts adafruit/Adafruit_IO_Arduino#165
**Why?**
The "Arduino Release v2.0.9 based on ESP-IDF v4.4.4" PR https://github.com/espressif/arduino-esp32/pull/8147 is to "revert to the previous definition of FPSTR and F macros". In #165, we patched this breaking change. This pull request is reverting the patch.
> Revert "Fix connectErrorString return type for ESP-32 BSP 2.0.8"

- library.properties
- src/AdafruitIO_WiFi.h
- src/wifi/AdafruitIO_Arduino_RenesasUno.h
This pull request adds support for Arduino Renesas Uno WiFi Rev 4 and Arduino Minima boards to the Adafruit IO Arduino library, enabling these devices to connect to Adafruit IO. 
* Added a new network interface in `src/wifi/AdafruitIO_Arduino_RenesasUno.h` to provide Adafruit IO connectivity using the R4 Uno's WiFiS3 builtin library.
Tested on hardware against Arduino Uno R4 WiFi board
> Add compatibility for Arduino R4 WiFi and Minima
